---
title: "Reading Delimited Data"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

## Task 2: Reading Delimited Data

#### Glass Data:

```{r}

library(tidyverse)
# read in data from URL and specify col names
glass_data <- read_csv("https://www4.stat.ncsu.edu/~online/datasets/glass.data", col_names = c("ID","RI","Na","Mg","Al","Si","K","Ca","Ba","Fe","TypeOfGlass"))

glass_data


```

Use chain to overwrite *Type of Glass* column and keep *Fe* less than 0.2 and *Type of Glass* as either tableware or headlamps:

```{r}

library(dplyr)

glass_data2 <- glass_data |>
  mutate(
    TypeOfGlass = case_when(
      TypeOfGlass == 1 ~ "building_windows_float_processed",
      TypeOfGlass == 2 ~ "building_windows_non_float_processed",
      TypeOfGlass == 3 ~ "vehicle_windows_float_processed",
      TypeOfGlass == 4 ~ "vehicle_windows_non_float_processed",
      TypeOfGlass == 5 ~ "containers",
      TypeOfGlass == 6 ~ "tablewares",
      TypeOfGlass == 7 ~ "headlamps",
      TRUE             ~ "other"
    )
  ) |>
  filter(Fe < 0.2) |>
  filter(TypeOfGlass == "tablewares" | TypeOfGlass == "headlamps")
   
glass_data2
```

#### Yeast Data:

```{r}
library(tidyverse)
# read in yeast space delimited file from URL
yeast_data <- read_table("https://www4.stat.ncsu.edu/~online/datasets/yeast.data", col_names = c("seq_name","mcg","gvh", "alm","mit","erl","pox","vac","nuc","class"))
 
yeast_data

#add mean and median to each numeric variable (mcg, gvh, alm, mit, erl, pox, and vac) by class grouping
yeast_data2 <- yeast_data |>
  select(-seq_name, -nuc) |>
  group_by(class) |>
  mutate(across(where(is.numeric), mean, .names = "mean_{.col}"))
  
```
